
(cl:in-package :asdf)

(defsystem "yhs_can_msgs-msg"
  :depends-on (:roslisp-msg-protocol :roslisp-utils )
  :components ((:file "_package")
    (:file "bms_fb" :depends-on ("_package_bms_fb"))
    (:file "_package_bms_fb" :depends-on ("_package"))
    (:file "bms_flag_fb" :depends-on ("_package_bms_flag_fb"))
    (:file "_package_bms_flag_fb" :depends-on ("_package"))
    (:file "ctrl_cmd" :depends-on ("_package_ctrl_cmd"))
    (:file "_package_ctrl_cmd" :depends-on ("_package"))
    (:file "ctrl_fb" :depends-on ("_package_ctrl_fb"))
    (:file "_package_ctrl_fb" :depends-on ("_package"))
    (:file "free_ctrl_cmd" :depends-on ("_package_free_ctrl_cmd"))
    (:file "_package_free_ctrl_cmd" :depends-on ("_package"))
    (:file "io_cmd" :depends-on ("_package_io_cmd"))
    (:file "_package_io_cmd" :depends-on ("_package"))
    (:file "io_fb" :depends-on ("_package_io_fb"))
    (:file "_package_io_fb" :depends-on ("_package"))
    (:file "l_wheel_fb" :depends-on ("_package_l_wheel_fb"))
    (:file "_package_l_wheel_fb" :depends-on ("_package"))
    (:file "r_wheel_fb" :depends-on ("_package_r_wheel_fb"))
    (:file "_package_r_wheel_fb" :depends-on ("_package"))
  ))